config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root :to => redirect('users')
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end

  # API endpoints
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  attribute :comments_counter, default: 0
  attribute :likes_counter, default: 0

  after_save :increment_posts_counter
  after_destroy :decrement_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates_presence_of :text
  validates_numericality_of :comments_counter, :likes_counter, only_integer: true, greater_than_or_equal_to: 0

  # Returns the 5 most recent comments for the post
  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def increment_posts_counter
    author.increment!(:posts_counter)
  end

  def decrement_posts_counter
    author.decrement!(:posts_counter)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::ApplicationController
  def index
    @posts = Post.where(author_id: params[:user_id])
    render json: @posts, status: 200
  end

  def show
    @post = Post.where(id: params[:id])
    render json: @post, status: 200
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.all
    @user = User.find(params[:user_id])
    @posts = Post.includes([:author]).includes([:comments]).where(author: @user).order(updated_at: :desc)
    @comments = Comment.all
  end

  def show
    @users = User.all
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @comments = Comment.all
    @new_comment = Comment.new
    @like = Like.new
  end

  def new
    @new_post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    if @post.save
      redirect_to user_path(current_user.id), notice: 'You created a post!'
    else
      redirect_to root_path
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy!
    redirect_to user_path(@post.author), notice: 'You deleted a post!'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :author)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_render_type(post)
    if current_page?(user_post_path(post.author, post))
      "<h4 class='display-6 inline'>#{post.title}</h4> by #{link_to(post.author.name, @user,
                                                                    class: 'inline')}".html_safe
    else
      link_to(content_tag(:h4, post.title, class: 'display-6'), "posts/#{post.id}")
    end
  end

  def render_like_btn(post)
    return unless current_page?(user_post_path(post.author, post))

    return unless user_signed_in?

    pre_like = @post.likes.find { |like| like.user_id == current_user.id }
    if pre_like
      button_to(image_tag('heart-solid.svg', width: 30), user_post_like_path(@user, post, pre_like), method: :delete,
                                                                                                     class: 'like-btn')
    else
      button_to(image_tag('heart-regular.svg', width: 30), user_post_likes_path(@user, post, @like), method: :post,
                                                                                                     class: 'like-btn')
    end
  end

  def build_comments(post)
    return '<strong>No comments yet.</strong>'.html_safe if post.comments.empty?

    built_comments = ''

    if current_page?(user_post_path(post.author, post))
      post.comments.each do |comment|
        if can? :destroy, comment
          b = button_to(image_tag('trash.svg', size: '15x15'), user_post_comment_path(@user, post, comment),
                        method: :delete, class: 'trash-icon')
          built_comments += b
        end
        built_comments += "<strong>#{User.find(comment.author_id).name}:</strong> #{comment.text}<br>"
      end
    else
      post.recent_comments.each do |comment|
        built_comments += "<strong>#{User.find(comment.author_id).name}:</strong> #{comment.text}<br>"
      end
    end

    built_comments.html_safe
  end
end

app/views/posts/_new_comment.html.erb
<div class="row m-3 justify-content-center comments-row">
  <div class="col-md-12 col-lg-9 offset-md-1 show-card">
    <%= form_with(model: @new_comment, url: '/users/'+params[:user_id].to_s+'/posts/'+params[:id].to_s+'/comments', method: :post) do |form| %>
      <div class="mb-3">
        <%= form.label :comment, class: "form-label" %>
        <%= form.text_field :text, class: "form-control", required: true %>
      </div>
      <div>
        <%= form.submit "Leave Comment", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <%= render partial: "users/partials/user_card", locals: { user: @user } %>
  <% @posts.each do |post| %>
    <%= render partial: "posts/partials/post_card", locals: { post: post } %>
    <%= render partial: "posts/partials/comments_card", locals: { post: post } %>
  <% end %>
  <button type="button">Pagination</button>
</div>

app/views/posts/new.html.erb
<div class="show-card container">
<%= bootstrap_form_with(model: @new_post, url: user_posts_path, method: :post) do |form| %>
  <%= form.text_field :title, class: "form-control", required: true %>
  <%= form.text_area :text, rows: 15, class: "form-control", required: true %>
  <%= form.submit "Create Post", class: "btn btn-primary" %>
<% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <%= render partial: "posts/partials/post_card", locals: { post: @post, full: true } %>
  <%= render partial: "posts/partials/comments_card", locals: { post: @post } %>
  <%= render template: "comments/new" %>
</div>