config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root :to => redirect('users')
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end

  # API endpoints
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/views/layouts/_navigation.html.erb
<header class='d-flex justify-content-between align-items-end'>
  <%= link_to("", root_path, class: "nav-logo") %>
  <%= link_to("BlogOnRails", root_path, class: "nav-title display-1") %>

  <div class="nav-btns">
  <% if user_signed_in? %>
      <%= link_to "+ New Post", new_user_post_path(current_user), class: "btn btn-success" %>
      <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-primary" %>
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
  <% else %>
      <%= link_to "Sign In", new_user_session_path, class: "btn btn-primary" %>
      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
  <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <% flash.each do |type, msg| %>
      <div class="ms-5 me-5 alert alert-success" role="alert">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>